# Copyright (c) 2020 Alex Carrega <contact@alexcarrega.com>
# author = "alex Carrega <contact@alexcarrega.com>

[log.console]
level = "DEBUG"
# cspell:disable
format = "[%(levelstyle)s]]%(levelicon)s = %(levelname)-8s[/%(levelstyle)s] %(message)s"
# cspell:enable

[log.file]
path = "logs"
level = "DEBUG"
# cspell:disable
format = "[%(asctime)s] %(levelname)-8s %(calledfilename)s@%(calledfunction)s]%(calledlineno)05d %(message)s"
# cspell:enable
rotation = "00:00"
retention = "10 days"
compression = "zip"

[log.net]
level = "INFO"
# cspell:disable
format = "[%(asctime)s] %(levelname)-8s %(calledfilename)s@%(calledfunction)s]%(calledlineno)05d %(message)s"
# cspell:enable
host = "0.0.0.0"
port= 8765

[log.logger]
__default__ = "DEBUG"
service = "INFO"
test = "DEBUG"

[style]
description = "yellow"
hostname = "yellow"
name = "yellow"
partner = "yellow"
username = "yellow"
password = "red"
port = "cyan"
stage = "green"
started = "green"
last_heartbeat = "green"
id = "blue"
status = "blue"
type_id = "purple"
exec_env_id = "purple"
network_link_id = "purple"
agent_catalog_id = "purple"
ebpf_program_catalog_id = "purple"
agent_instance_id = "purple"
ebpf_program_instance_id = "purple"
cmd = "yellow"
code = "cyan"
message = "yellow"
expr = "yellow"
target = "blue"

[style.enabled]
True = "green"
False = "red"

[style.daemon]
True = "green"
False = "red"

[style.error]
True = "red"
False = "green"

[icon]
id = "id"
type_id = "id"
exec_env_id = "id"
network_link_id = "id"
agent_catalog_id = "id"
ebpf_program_catalog_id = "id"
agent_instance_id = "id"
ebpf_program_instance_id = "id"
hostname = "computer"
lcp = "package"
partner = "copyright"
stage = "ribbon"
password = "secret"
username = "man"
last_heartbeat = "date"
started = "date"
port = 1234
enabled = "recycle"
description = "memo"
name = "pencil2"
status = "signal_strength"
config = "clipboard"
cmd = "small_blue_diamond"
resources = "briefcase"
daemon = "wavy_dash"
code = 1234
error = "warning"
message = "memo"
query = "mag"
where = "barber"
equals = "white_flower"
and = "star2"
expr = "curly_loop"
target = "arrow_right"

[vars]
cb_manager = "http://130.251.17.130:5000"

[endpoints.exec-env]
title = "Execution Environments"
uri = "{cb_manager}/exec-env"
help = "List of Execution Environments."

[endpoints.exec-env-type]
title = "Execution Environment Types"
uri = "{cb_manager}/type/exec-env"
help = "List of Execution Environment Types."

[endpoints.network-link]
title = "Network Links"
uri = "{cb_manager}/network-link"
help = "List of Network Links."

[endpoints.network-link-type]
title = "Network Link Types"
uri = "{cb_manager}/type/network-link"
help = "List of Network Link Types."

[endpoints.connection]
title = "Connections"
uri = "{cb_manager}/connections"
help = "List of Connections."
[endpoints.agent-catalog]
title = "Agent Catalog"
uri = "{cb_manager}/catalog/agent"
help = "List of available Agents in the Catalog."

[endpoints.agent-instance]
title = "Agent Instances"
uri = "{cb_manager}/instance/agent"
help = "List of Agent Instances deployed in the Execution Environments."

[endpoints.ebpf-program-catalog]
title = "eBPF Program Catalog"
uri = "{cb_manager}/catalog/ebpf-program"
help = "List of available eBPF-Program in the Catalog."

[endpoints.ebpf-program-instance]
title = "eBPF Program Instances"
uri = "{cb_manager}/instance/ebpf-program"
help = "List of eBPF-Program Instances deployed in the Execution Environments."

[endpoints.data]
title = "Data"
uri = "{cb_manager}/data"
help = "List of Data records."

[endpoints.event]
title = "Events"
uri = "{cb_manager}/event"
help = "List of Event records."
